In [ ]:
# Challenge 1: Counting Vowels in a Sentence
# Description
# Write a function that counts how many vowels (a, e, i, o, u, case insensitive) appear in a given sentence.
# Roles
# •	Coder: Implement count_vowels(sentence) using a for loop.
# •	Tester: Prepare ≥5 test cases (empty string, no vowels, all vowels, mixed case).
# •	Presenter: Demonstrate the function on sample inputs and explain the loop logic.

#create a function that accepts user input as its parameter (sentence)
def count_vowels(sentence):

    #declare a variable to store the vowels ,to handle case insensitivity for both uppercase and lowercase
    vowels = "aeiouAEIOU"

    #initialize the value of count to a zero
    count = 0

    #create a for loop that iterates through the sentence and also have an instance variable(char) to help you iterate
    for char in sentence:

      #create a branching statement that confirms if there are vowels inside the sentence (string)
        if char in vowels:

          #if the condition is true vowels are going to be counted as the loop iterates ,
          #this updates the count variable by one upon each iteration if condition is meet

            count += 1
    return count

#ask for user input and store it in the variable sentence
sentence=input("enter a sentence:")

#Call the function and specify the arguments ie(sentence),use a variable to store the value upon a return
result = count_vowels(sentence)

#display the total number of vowels in the sentence
print(f"Number of vowels in the sentence: {result}")

enter a sentence:welcome to eldo hub
Number of vowels in the sentence: 7

In [ ]:
# Challenge 2: Detecting Prime Numbers in a Range
# Description
# Given two integers start and end, print all primes between them (inclusive).
# Roles
# •	Coder: Implement is_prime(n) and loop with for n in range(start, end+1).
# •	Tester: Verify edge cases (start > end, ranges with no primes, small ranges).
# •	Presenter: Explain the nested loops and early exit via break.

#declare and define a  that accept parameters for the range of numbers to check if its prime
def print_primes_in_range(start, end):

#prints prime numbers within the users  range
  print(f"\nPrime numbers between {start} and {end+1} are")

  #outer for loop that increments the range values by one
  for num in range(start,end + 1):

       #checks if the instance variable is less than one
        if num > 1:

            for i in range(2, int(num**0.5) + 1):
                if (num % i) == 0:
                    break
            else:
                print(f"{num}")

# Example usage: print prime numbers between 20 and 50
start=int(input("enter start value"))
end=int(input("enter end value"))

print_primes_in_range(start,end)

enter start value10
enter end value70

Prime numbers between 10 and 71 are
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67

In [ ]:
# Guess and Check with Limited Attempts
# Description
# Hard code a secret number between 1–50. Prompt the user up to 5 times to guess it. After each guess, print “Too low”, “Too high”, or congratulate and exit. If all attempts fail, reveal the secret.
# Roles
# •	Coder: Write a while loop controlling attempts and branching on guess comparison.
# •	Tester: Simulate correct and incorrect guess sequences; test boundary guesses.
# •	Presenter: Walk through loop flow and the else: clause on the while
secret_number=20
attempts=0

while attempts<5:
  guess=int(input("Guess a number:"))
  if guess < secret_number:
    print("Too low")
  elif guess > secret_number:
    print("Too high")
  elif guess ==secret_number:
    print("congartulations you made the correct guess")
    break
else:
    print(f"maximum attempts reached the secret number:{secret_number}")

Guess a number:12
Too low
Guess a number:56
Too high
Guess a number:77
Too high
Guess a number:78
Too high
Guess a number:88
Too high
maximum attempts reached the secret number:20

In [ ]:
# Challenge 4: Nested Loops for Pattern Printing
# Description
# Print a multiplication table up to n × m (e.g., n=4, m=5), formatting as a grid.
# Roles
# •	Coder: Use nested for loops; format output with f strings.
# •	Tester: Check for various table sizes (1×1, 3×3, 4×7).
# •	Presenter: Demonstrate row and column iteration and explain nested flow.


for i in range(1,15):
  print(f"\n")
  print(f"multiplication table for {i}\n")
  for j in range(1,10+1):
    result=i*j
    print(f"{i}*{j}={result}")

multiplication table for 1

1*1=1
1*2=2
1*3=3
1*4=4
1*5=5
1*6=6
1*7=7
1*8=8
1*9=9
1*10=10


multiplication table for 2

2*1=2
2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
2*10=20


multiplication table for 3

3*1=3
3*2=6
3*3=9
3*4=12
3*5=15
3*6=18
3*7=21
3*8=24
3*9=27
3*10=30


multiplication table for 4

4*1=4
4*2=8
4*3=12
4*4=16
4*5=20
4*6=24
4*7=28
4*8=32
4*9=36
4*10=40


multiplication table for 5

5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
5*10=50


multiplication table for 6

6*1=6
6*2=12
6*3=18
6*4=24
6*5=30
6*6=36
6*7=42
6*8=48
6*9=54
6*10=60


multiplication table for 7

7*1=7
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
7*10=70


multiplication table for 8

8*1=8
8*2=16
8*3=24
8*4=32
8*5=40
8*6=48
8*7=56
8*8=64
8*9=72
8*10=80


multiplication table for 9

9*1=9
9*2=18
9*3=27
9*4=36
9*5=45
9*6=54
9*7=63
9*8=72
9*9=81
9*10=90


multiplication table for 10

10*1=10
10*2=20
10*3=30
10*4=40
10*5=50
10*6=60
10*7=70
10*8=80
10*9=90
10*10=100


multiplication table for 11

11*1=11
11*2=22
11*3=33
11*4=44
11*5=55
11*6=66
11*7=77
11*8=88
11*9=99
11*10=110


multiplication table for 12

12*1=12
12*2=24
12*3=36
12*4=48
12*5=60
12*6=72
12*7=84
12*8=96
12*9=108
12*10=120


multiplication table for 13

13*1=13
13*2=26
13*3=39
13*4=52
13*5=65
13*6=78
13*7=91
13*8=104
13*9=117
13*10=130


multiplication table for 14

14*1=14
14*2=28
14*3=42
14*4=56
14*5=70
14*6=84
14*7=98
14*8=112
14*9=126
14*10=140


multiplication table for 1

1*1=1
1*2=2
1*3=3
1*4=4
1*5=5
1*6=6
1*7=7
1*8=8
1*9=9
1*10=10


multiplication table for 2

2*1=2
2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
2*10=20


multiplication table for 3

3*1=3
3*2=6
3*3=9
3*4=12
3*5=15
3*6=18
3*7=21
3*8=24
3*9=27
3*10=30


multiplication table for 4

4*1=4
4*2=8
4*3=12
4*4=16
4*5=20
4*6=24
4*7=28
4*8=32
4*9=36
4*10=40


multiplication table for 5

5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
5*10=50


multiplication table for 6

6*1=6
6*2=12
6*3=18
6*4=24
6*5=30
6*6=36
6*7=42
6*8=48
6*9=54
6*10=60


multiplication table for 7

7*1=7
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
7*10=70


multiplication table for 8

8*1=8
8*2=16
8*3=24
8*4=32
8*5=40
8*6=48
8*7=56
8*8=64
8*9=72
8*10=80


multiplication table for 9

9*1=9
9*2=18
9*3=27
9*4=36
9*5=45
9*6=54
9*7=63
9*8=72
9*9=81
9*10=90


multiplication table for 10

10*1=10
10*2=20
10*3=30
10*4=40
10*5=50
10*6=60
10*7=70
10*8=80
10*9=90
10*10=100


multiplication table for 11

11*1=11
11*2=22
11*3=33
11*4=44
11*5=55
11*6=66
11*7=77
11*8=88
11*9=99
11*10=110


multiplication table for 12

12*1=12
12*2=24
12*3=36
12*4=48
12*5=60
12*6=72
12*7=84
12*8=96
12*9=108
12*10=120


multiplication table for 13

13*1=13
13*2=26
13*3=39
13*4=52
13*5=65
13*6=78
13*7=91
13*8=104
13*9=117
13*10=130


multiplication table for 14

14*1=14
14*2=28
14*3=42
14*4=56
14*5=70
14*6=84
14*7=98
14*8=112
14*9=126
14*10=140