In [ ]:
def clean_names(names):
    unique_names = list(set(names))       # Remove duplicates using set
    unique_names.sort()                   # Sort alphabetically
    return unique_names

#  Example usage:
names_list = ["Alice", "Bob", "Alice", "David", "Charlie", "Bob"]
print(clean_names(names_list))  # ➜ ['Alice', 'Bob', 'Charlie', 'David']

In [ ]:
L1 = ['sun']
L2 = L1
L1 = ['moon']
print(L2)  # ➜ ['sun']

In [ ]:
# Step 1: Create a list of 10 names (with duplicates)
names = ["Anna", "Brian", "Cathy", "Anna", "Derek", "Eva", "Brian", "George", "Hilda", "Cathy"]

# Step 2: Remove duplicates using set
unique_names = list(set(names))

# Step 3: Sort alphabetically
unique_names.sort()

# Step 4: Print the result
print("Sorted unique names:")
print(unique_names)